---
- name: Установка Docker
  hosts: all
  become: true

  tasks:
    - name: Обновление кэша apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Установка необходимых пакетов
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Создание директории keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Удаление старого GPG ключа Docker если существует
      file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

    - name: Загрузка GPG ключа Docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Установка apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Получение названия релиза Ubuntu
      command: lsb_release -cs
      register: ubuntu_release
      changed_when: false

    - name: Получение архитектуры системы
      command: dpkg --print-architecture
      register: system_arch
      changed_when: false

    - name: Добавление репозитория Docker
      apt_repository:
        repo: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_release.stdout }} stable"
        state: present
        filename: docker
        update_cache: yes

    - name: Установка пакетов Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Запуск и включение сервиса Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Добавление текущего пользователя в группу docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
