---
- name: Установка K3s с Calico
  hosts: all
  become: true

  tasks:
    - name: Проверка конфигурации DNS
      shell: cat /etc/resolv.conf
      register: dns_config

    - name: Отображение конфигурации DNS
      debug:
        msg: "Текущая конфигурация DNS: {{ dns_config.stdout_lines }}"

    - name: Добавление localhost в файл hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 localhost"
        state: present
      ignore_errors: true

    - name: Обновление кэша apt и пакетов
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Установка CalicoCtl
      shell: |
        curl -L https://github.com/projectcalico/calico/releases/latest/download/calicoctl-linux-amd64 -o calicoctl
        chmod +x calicoctl
        mv calicoctl /usr/local/bin/

    - name: Установка K3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init --disable traefik --flannel-backend=none --disable-network-policy" sh -

    - name: Ожидание готовности K3s
      wait_for:
        port: 6443
        host: localhost
        delay: 10
        timeout: 300

    - name: Настройка Kubeconfig
      shell: |
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        chown $(id -u):$(id -g) ~/.kube/config
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

    - name: Установка Calico Operator
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.2/manifests/operator-crds.yaml
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.2/manifests/tigera-operator.yaml

    - name: Ожидание готовности Calico Operator
      pause:
        seconds: 45

    - name: Установка Calico
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.2/manifests/custom-resources.yaml
        kubectl patch installation default --type=merge --patch='{"spec":{"calicoNetwork":{"contai nerIPForwarding":"Enabled"}}}'

    - name: Ожидание готовности Calico
      pause:
        seconds: 60

    - name: Установка Nginx Ingress Controller
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml

    - name: Установка Cert Manager
      shell: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.yaml
