---
- name: Установка и настройка NGINX
  hosts: all
  become: true

  tasks:
    - name: Обновление кэша apt и пакетов
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Установка пакета NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Установка пакета Certbot
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Запуск сервиса NGINX
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Перезапуск NGINX
      service:
        name: nginx
        state: restarted
