---
- name: Install and configure NGINX
  hosts: all  
  become: true       

  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Install NGINX package
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Certbot package
      apt:
        name: 
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: yes
    

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
