---
- name: "Создание и управление пользователем"
  hosts: all
  become: true
  gather_facts: false

  vars:
    sudoers_dropin_path: "/etc/sudoers.d"

  pre_tasks:
    - name: Проверка установки sudo
      package:
        name: sudo
        state: present

  tasks:
    - name: Создание учетной записи пользователя
      user:
        name: "{{ user_name }}"
        state: "{{ user_state }}"
        uid: "{{ user_uid if (user_uid is defined and user_uid) else omit }}"
        shell: "{{ user_shell }}"
        create_home: "{{ user_create_home }}"
        groups: "{{ (user_groups | default([])) | join(',') if (user_groups | default([]) | length > 0) else omit }}"
        append: true
        password: "{{ user_password_hash if (user_password_hash is defined and user_password_hash) else omit }}"

    - name: Создание директории .ssh при наличии домашней папки
      file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0700"
      when: user_state == 'present' and user_create_home | bool

    - name: Установка authorized_keys для пользователя
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ item }}"
        manage_dir: true
      loop: "{{ user_ssh_public_keys | default([]) }}"
      when: user_state == 'present' and (user_ssh_public_keys | default([])) | length > 0

    - name: Настройка sudo без пароля (drop-in файл)
      copy:
        dest: "{{ sudoers_dropin_path }}/{{ user_name }}"
        content: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: "0440"
        validate: "visudo -cf %s"
      when: user_state == 'present' and (user_sudo | bool)

    - name: Удаление sudoers drop-in когда пользователь не должен иметь sudo
      file:
        path: "{{ sudoers_dropin_path }}/{{ user_name }}"
        state: absent
      when: user_state == 'present' and not (user_sudo | bool)

    - name: Удаление sudoers drop-in пользователя при отсутствии пользователя
      file:
        path: "{{ sudoers_dropin_path }}/{{ user_name }}"
        state: absent
      when: user_state == 'absent'
